language: csharp
solution: PokeClone.sln
install:
- sudo apt-get install -y gtk-sharp2
- cd src
- nuget restore PokeClone.sln
- nuget install NUnit.Runners -Version 3.4.1 -OutputDirectory testrunner
mono:
- latest
script:
- xbuild /p:Configuration=Release /p:DefineConstants=TRAVIS PokeClone.sln
- mono ./testrunner/NUnit.ConsoleRunner.3.4.1/tools/nunit3-console.exe ./BattleModeTest/bin/AnyCPU/Release/BattleModeTest.dll
  ./GameEngineTest/bin/AnyCPU/Release/GameEngineTest.dll ./MainModeTest/bin/AnyCPU/Release/MainModeTest.dll
- 7z a PokeClone-Linux.zip ./PokemonGame/bin/AnyCPU/Release/*.dll ./PokemonGame/bin/AnyCPU/Release/*.exe ./PokemonGame/bin/AnyCPU/Release/Content
addons:
  apt:
    packages:
    - p7zip-full
deploy:
  provider: releases
  api_key:
    secure: A3zYGrQHdKdwJ7CCXHXhOxDG0jp6MHUGqGIMv41BJo1596hwajLwARsoWCBBddms8IeQRBnsahFdu8/2ATBgvqlkxAbRQ4xNLuYPhLeX+n1JzyNYU4IMkTxSxoTOOG4ZWxrEGDtLEPF816r/HiOQgoNs2CZ56NGthQzIyOHscIE5s91lcEAwfCDmv8SxhsbbakRGn9RKfohJkH3fzHKYVkjOKQpNkqxeu/46RI+SKvd3GpB6p+P6d632pOAdsYJWUMwBke19YJ5grIAaH3aiZu8hasx66ppEkaq6enTPilTNlvTCBRDdTK+LbIz11qMshgW7hm0PJn+js4utfvSexyiy+lynu5aFx7DZC4cjGmeEg0synvxK9NVomXDc4GQiNvBlDNUUj1MwSVkC6/XmcdN6zRkg51eWFmizBQcp2tmnwFsIqVrIEBjFY6AiaXD347EpJMzZvtFu34kAJEMJpSyWg4sYx6K7UJQzvtW1urwMMlbvYRK8K6+RBnhaK3qFyTy82dbXdK+wSQ7Ffe/BUgq2v4AJ6ZfbfSgDoMss8mqHB+T7NrVVnRkK1VT/0NOoEJqdpssogCnaMZVSrJC8FnFmRYS6s21dSGoWAvQQgGwJysCglndgnFao5/TeC+QFBoFwRwsqwz/U5A2ZpRFTTRS/BYpHnhz8/1sd9AGAGS8=
  file: PokeClone-Linux.zip
  on:
    repo: Nexus87/PokeClone
    tags: true
