language: csharp
solution: PokeClone.sln
install:
  - mono ./Protobuild.exe --generate Linux
  - nuget install NUnit.Runners -Version 3.2.0 -OutputDirectory testrunner
mono:
  - latest
script:
  - xbuild /p:Configuration=Debug /p:DefineConstants=TRAVIS PokeClone.Linux.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.2.0/tools/nunit3-console.exe ./BattleLibTest/bin/Linux/AnyCPU/Debug/BattleLibTest.dll ./GameEngineTest/bin/Linux/AnyCPU/Debug/GameEngineTest.dll