language: csharp
solution: PokeClone.sln
install:
  - mono ./Protobuild --generate Linux
  - nuget install NUnit.Runners -Version 3.2.0 -OutputDirectory testrunner
mono:
  - latest
script:
  - xbuild /p:Configuration=Debug PokeClone.Linux.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.2.0/tools/nunit3-console.exe ./BattleLibTest/bin/DebugContentPrebuild/BattleLibTest.dll ./GameEngineTest/bin/DebugContentPrebuild/GameEngineTest.dll